Repository activeadmin/activeadmin, pull requests merged in 2020-12, with the labels that each got.

#6536 Pick up upstream fixes in devise templates
  app/views/active_admin/devise/mailer/reset_password_instructions.html.erb
  app/views/active_admin/devise/mailer/unlock_instructions.html.erb
Labels: type: bug fix

#6583 Fix `has_many` syntax in forms documentation
  docs/5-forms.md
Labels: type: documentation

#6584 Remove sassc and sprockets runtime dependencies
  Gemfile
  Gemfile.lock
  activeadmin.gemspec
  gemfiles/rails_52/Gemfile
  gemfiles/rails_52/Gemfile.lock
  gemfiles/rails_60_turbolinks/Gemfile
  gemfiles/rails_60_turbolinks/Gemfile.lock
  gemfiles/rails_60_webpacker/Gemfile
  gemfiles/rails_60_webpacker/Gemfile.lock
  lib/active_admin.rb
  lib/active_admin/engine.rb
  spec/support/rails_template.rb
  tasks/test_application.rb
Labels: type: breaking change
