Repository activeadmin/activeadmin, pull requests merged in 2021-03, with the labels that each got.

#5660 Use collection length instead of running COUNTs for limited collections
  lib/active_admin/helpers/collection.rb
  spec/unit/views/components/paginated_collection_spec.rb
Labels: type: enhancement

#6872 Clarify docs on user setup
  docs/0-installation.md
Labels: type: documentation

#6873 Change Korean i18n that misleading
  config/locales/ko.yml
Labels: type: i18n
