Repository activeadmin/activeadmin, pull requests merged in 2022-02, with the labels that each got.

#7127 Show ransackable_scopes filters in search results
  features/index/filters.feature
  lib/active_admin/filters/active_sidebar.rb
  lib/active_admin/views/components/active_filters_sidebar_content.rb
  spec/support/templates/models/post.rb
Labels: bug, ready, type: bug fix

#7205 Don't apply sorting to collection until after scoping
  lib/active_admin/resource_controller/data_access.rb
Labels: type: enhancement

#6954 Load favicon from Webpacker assets when use_webpacker is set to true
  lib/active_admin/views/pages/base.rb
  spec/support/rails_template.rb
Labels: type: enhancement

#7332 Fix frozen string error when downloading CSV and streaming disabled
  features/index/format_as_csv.feature
  features/step_definitions/format_steps.rb
  lib/active_admin/resource_controller/streaming.rb
Labels: ready, type: bug fix

#7340 Remove deprecation warning using controller filters inside initializer
  lib/active_admin/application.rb
  lib/active_admin/base_controller.rb
  lib/active_admin/devise.rb
Labels: type: enhancement

#7350 Vendor normalize 8.0.1
  app/assets/stylesheets/active_admin/_normalize.scss
Labels: ready

#7349 Apply `box-sizing: border-box` globally
  app/assets/stylesheets/active_admin/_base.scss
  app/assets/stylesheets/active_admin/_forms.scss
  app/assets/stylesheets/active_admin/components/_date_picker.scss
  app/assets/stylesheets/active_admin/components/_dropdown_menu.scss
  app/assets/stylesheets/active_admin/structure/_title_bar.scss
Labels: ready

#7351 Get ready for 2.10.1 release
  CHANGELOG.md
  Gemfile.lock
  gemfiles/rails_60/Gemfile.lock
  gemfiles/rails_61_turbolinks/Gemfile.lock
  gemfiles/rails_61_webpacker/Gemfile.lock
  lib/active_admin/version.rb
  package.json
Labels: ready

#7352 Add last minute PRs to 2.10.1 changelog
  CHANGELOG.md
Labels: ready
