Repository activeadmin/activeadmin, pull requests merged in 2022-01, with the labels that each got.

#7289 Small follow up to ruby 2.5 support drop
  .github/workflows/ci.yaml
  .github/workflows/daily.yaml
  tasks/bug_report_template.rb
Labels: ready

#7095 Resolve dart sass deprecation warning for division
  app/assets/stylesheets/active_admin/_forms.scss
Labels: type: enhancement

#7275 Test with Ruby 3.0 and Ruby 3.1
  .github/workflows/ci.yaml
  Gemfile
  Gemfile.lock
  gemfiles/rails_52/Gemfile
  gemfiles/rails_52/Gemfile.lock
  gemfiles/rails_60/Gemfile
  gemfiles/rails_60/Gemfile.lock
  gemfiles/rails_61_turbolinks/Gemfile
  gemfiles/rails_61_turbolinks/Gemfile.lock
  gemfiles/rails_61_webpacker/Gemfile
  gemfiles/rails_61_webpacker/Gemfile.lock
  spec/support/active_admin_integration_spec_helper.rb
  spec/unit/filters/active_filter_spec.rb
  spec/unit/filters/filter_form_builder_spec.rb
  spec/unit/form_builder_spec.rb
  spec/unit/localizers/resource_localizer_spec.rb
  spec/unit/pretty_format_spec.rb
  spec/unit/view_helpers/display_helper_spec.rb
  spec/unit/views/components/attributes_table_spec.rb
  spec/unit/views/components/status_tag_spec.rb
  spec/unit/views/components/table_for_spec.rb
  tasks/bug_report_template.rb
Labels: ready

#7293 Drop rails 5.2 support
  .github/dependabot.yml
  .github/workflows/ci.yaml
  .github/workflows/daily.yaml
  .rubocop.yml
  Gemfile.lock
  activeadmin.gemspec
  gemfiles/rails_52/Gemfile
  gemfiles/rails_52/Gemfile.lock
  gemfiles/rails_60/Gemfile.lock
  gemfiles/rails_61_turbolinks/Gemfile.lock
  gemfiles/rails_61_webpacker/Gemfile.lock
  lib/active_admin/dependency.rb
  spec/support/active_admin_integration_spec_helper.rb
Labels: ready, type: dependency change
