Repository activeadmin/activeadmin, pull requests merged in 2022-04, with the labels that each got.

#7170 Fix disappearing BOM option for `CSVBuilder`
  features/index/format_as_csv.feature
  features/step_definitions/format_steps.rb
  features/step_definitions/web_steps.rb
  lib/active_admin/csv_builder.rb
Labels: ready, type: bug fix

#7377 Don't mention webpacker as the default asset generator in Rails
  docs/0-installation.md
Labels: ready, type: documentation

#7336 Avoid duplicate work when downloading CSV
  lib/active_admin/csv_builder.rb
  lib/active_admin/resource_controller/data_access.rb
  spec/unit/csv_builder_spec.rb
  spec/unit/resource_controller/data_access_spec.rb
Labels: ready, type: performance

#7144 Fix pundit namespace detection
  lib/active_admin/pundit_adapter.rb
  spec/spec_helper.rb
  spec/support/shared_contexts/capture_stderr.rb
  spec/unit/action_builder_spec.rb
  spec/unit/pundit_adapter_spec.rb
Labels: type: bug fix

#7453 Add Ransack 3 compatibility
  Gemfile.lock
  activeadmin.gemspec
  gemfiles/rails_60/Gemfile.lock
  gemfiles/rails_61/Gemfile.lock
  gemfiles/rails_61_turbolinks/Gemfile.lock
  gemfiles/rails_61_webpacker/Gemfile.lock
Labels: type: enhancement

#7455 Use squash merge strategy for mergify
  .github/mergify.yml
Labels: ready

#7457 Get ready for 2.12.0 release
  CHANGELOG.md
  Gemfile.lock
  gemfiles/rails_60/Gemfile.lock
  gemfiles/rails_61/Gemfile.lock
  gemfiles/rails_61_turbolinks/Gemfile.lock
  gemfiles/rails_61_webpacker/Gemfile.lock
  lib/active_admin/version.rb
  package.json
  spec/changelog_spec.lint.rb
  tasks/changelog.rb
Labels: ready
