Repository activeadmin/activeadmin, pull requests merged in 2022-05, with the labels that each got.

#7476 Drop rails 6.0 support
  .github/dependabot.yml
  .github/workflows/ci.yaml
  .github/workflows/daily.yaml
  .rubocop.yml
  CONTRIBUTING.md
  Gemfile.lock
  activeadmin.gemspec
  gemfiles/rails_60/Gemfile
  gemfiles/rails_60/Gemfile.lock
  gemfiles/rails_61/Gemfile.lock
  gemfiles/rails_61_turbolinks/Gemfile.lock
  gemfiles/rails_61_webpacker/Gemfile.lock
Labels: ready, type: dependency change

#7479 Fix pundit performance
  lib/active_admin/pundit_adapter.rb
  spec/unit/pundit_adapter_spec.rb
Labels: ready, type: performance

#7480 Get ready for 2.13.0 release
  CHANGELOG.md
  Gemfile.lock
  gemfiles/rails_61/Gemfile.lock
  gemfiles/rails_61_turbolinks/Gemfile.lock
  gemfiles/rails_61_webpacker/Gemfile.lock
  lib/active_admin/version.rb
  package.json
Labels: ready

#7488 Honor load paths order when loading admin files
  lib/active_admin/application.rb
  spec/unit/application_spec.rb
Labels: type: bug fix

#7498 Get ready for 2.13.1 release
  CHANGELOG.md
  Gemfile.lock
  gemfiles/rails_61/Gemfile.lock
  gemfiles/rails_61_turbolinks/Gemfile.lock
  gemfiles/rails_61_webpacker/Gemfile.lock
  lib/active_admin/version.rb
  package.json
Labels: ready
