Repository activeadmin/activeadmin, pull requests merged in 2022-03, with the labels that each got.

#7341 Fix form SCSS variables no longer being defined in the outermost scope, so no longer being accessible
  app/assets/stylesheets/active_admin/_forms.scss
  app/assets/stylesheets/active_admin/mixins/_variables.scss
Labels: type: bug fix

#7392 Get ready for 2.11.0 release
  CHANGELOG.md
  Gemfile.lock
  gemfiles/rails_60/Gemfile.lock
  gemfiles/rails_61/Gemfile.lock
  gemfiles/rails_61_turbolinks/Gemfile.lock
  gemfiles/rails_61_webpacker/Gemfile.lock
  lib/active_admin/version.rb
  package.json
Labels: ready

#7394 Remove `insert_tag` from Form-Partial docs
  docs/5-forms.md
Labels: type: documentation

#7384 Add turbolinks support to has many js
  app/assets/javascripts/active_admin/base.js
  app/javascript/active_admin/initializers/has-many.js
  features/has_many.feature
  features/step_definitions/additional_web_steps.rb
Labels: ready, type: enhancement

#7401 Bump ransack from 2.5.0 to 2.6.0
  Gemfile.lock
Labels: dependencies, ruby

#7403 Bump rails from 7.0.2.2 to 7.0.2.3
  Gemfile.lock
Labels: dependencies, ruby
