Repository activeadmin/activeadmin, pull requests merged in 2023-07, with the labels that each got.

#7993 Improve Swedish translations
  config/locales/sv-SE.yml
Labels: type: i18n

#8009 Require Ransack v4
  Gemfile.lock
  activeadmin.gemspec
  gemfiles/rails_61/Gemfile.lock
  lib/active_admin/orm/active_record/comments/comment.rb
  spec/support/rails_template.rb
  spec/support/templates/models/blog/post.rb
  spec/support/templates/models/category.rb
  spec/support/templates/models/post.rb
  spec/support/templates/models/profile.rb
  spec/support/templates/models/tag.rb
  spec/support/templates/models/tagging.rb
  spec/support/templates/models/user.rb
  spec/unit/comments_spec.rb
Labels: type: breaking change

#8010 Remove custom Ransack predicates that were MetaSearch backports
  config/locales/ar.yml
  config/locales/az.yml
  config/locales/bg.yml
  config/locales/bs.yml
  config/locales/ca.yml
  config/locales/cs.yml
  config/locales/da.yml
  config/locales/de-CH.yml
  config/locales/de.yml
  config/locales/el.yml
  config/locales/en-CA.yml
  config/locales/en-GB.yml
  config/locales/en.yml
  config/locales/eo.yml
  config/locales/es-MX.yml
  config/locales/es.yml
  config/locales/fa.yml
  config/locales/fi.yml
  config/locales/fr.yml
  config/locales/he.yml
  config/locales/hr.yml
  config/locales/hu.yml
  config/locales/id.yml
  config/locales/it.yml
  config/locales/ja.yml
  config/locales/ko.yml
  config/locales/lt.yml
  config/locales/lv.yml
  config/locales/mk.yml
  config/locales/nb.yml
  config/locales/nl.yml
  config/locales/pl.yml
  config/locales/pt-BR.yml
  config/locales/pt-PT.yml
  config/locales/ro.yml
  config/locales/ru.yml
  config/locales/sk.yml
  config/locales/sv-SE.yml
  config/locales/tr.yml
  config/locales/uk.yml
  config/locales/vi.yml
  config/locales/zh-CN.yml
  config/locales/zh-TW.yml
  docs/12-arbre-components.md
  docs/3-index-pages.md
  features/index/filters.feature
  lib/active_admin.rb
  lib/active_admin/filters/active_filter.rb
  lib/active_admin/filters/forms.rb
  lib/active_admin/inputs/filters/base/search_method_select.rb
  lib/active_admin/inputs/filters/date_range_input.rb
  lib/active_admin/inputs/filters/numeric_input.rb
  lib/active_admin/inputs/filters/string_input.rb
  lib/active_admin/namespace_settings.rb
  lib/generators/active_admin/install/templates/active_admin.rb.erb
  lib/ransack_ext.rb
  spec/unit/filters/active_filter_spec.rb
  spec/unit/filters/filter_form_builder_spec.rb
  spec/unit/resource/routes_spec.rb
  spec/unit/views/components/index_list_spec.rb
Labels: type: breaking change

#6342 Use display name fallback if blank display name result
  lib/active_admin/view_helpers/display_helper.rb
  lib/active_admin/views/pages/show.rb
  spec/unit/view_helpers/display_helper_spec.rb
Labels: type: enhancement
