Repository activeadmin/activeadmin, pull requests merged in 2023-12, with the labels that each got.

#8117 Provide detail in DB statement timeout error for filters
  lib/active_admin/inputs/filters/select_input.rb
  spec/unit/filters/filter_form_builder_spec.rb
Labels: type: enhancement

#8137 Fix Ransack error with filters when ActiveStorage is used
  lib/active_admin/filters/formtastic_addons.rb
Labels: type: bug fix

#8132 Make sure menu creation does not modify menu options
  lib/active_admin/menu.rb
Labels: type: bug fix

#8163 Backport to 3-0 stable branch provide detail in DB statement timeout error for filters (#8117)
  lib/active_admin/inputs/filters/select_input.rb
  spec/unit/filters/filter_form_builder_spec.rb
Labels: type: enhancement

#8164 Backport to 3-0 stable branch ransack error with filters when ActiveStorage is used (#8137)
  lib/active_admin/filters/formtastic_addons.rb
Labels: type: bug fix

#8165 Backport to 3-0 stable branch support citext column type in string filter (#8089)
  lib/active_admin/filters/forms.rb
Labels: type: enhancement

#8166 Backport to 3-0 stable branch make sure menu creation does not modify menu options (#8132)
  lib/active_admin/menu.rb
Labels: type: bug fix

#8167 Backport to 3-0 stable branch protect against CSV Injection (#8161)
  lib/active_admin/csv_builder.rb
  spec/unit/csv_builder_spec.rb
Labels: type: security fix
