Repository activeadmin/activeadmin, pull requests merged in 2024-01, with the labels that each got.

#8211 Include vendor directory in gem release
  activeadmin.gemspec
Labels: type: bug fix

#8217 Vendor rails-ujs ESM JS
  config/importmap.rb
  vendor/javascript/rails_ujs_esm.js
Labels: type: enhancement

#8238 Ensure form presenter is applied on create/update actions
  app/controllers/active_admin/resource_controller.rb
  plugin.js
Labels: type bug fix

#8235 Improve Italian translation
  config/locales/it.yml
Labels: type enhancement
