Repository activeadmin/activeadmin, pull requests merged in 2024-08, with the labels that each got.

#8338 Add accessible names for navigation buttons
  UPGRADING.md
  app/views/active_admin/_main_navigation.html.erb
  app/views/active_admin/_site_header.html.erb
  config/locales/en.yml
  config/locales/it.yml
Labels: type enhancement, type template update

#8394 Support async_count for scopes
  lib/active_admin/async_count.rb
  lib/active_admin/scope.rb
  lib/active_admin/views/components/scopes.rb
  spec/unit/async_count_spec.rb
  spec/unit/scope_spec.rb
  spec/unit/views/components/scopes_spec.rb
Labels: type enhancement

#8439 Improve form f.inputs attributes rendering
  lib/active_admin/views/components/active_admin_form.rb
  spec/unit/form_builder_spec.rb
Labels: type bug fix

#8423 Add tbody_html and row_html options to TableFor and IndexAsTable
  docs/3-index-pages/index-as-table.md
  lib/active_admin/views/components/table_for.rb
  lib/active_admin/views/index_as_table.rb
  spec/unit/views/components/table_for_spec.rb
Labels: type enhancement

#8442 Fix batch action with partial and no confirm doesn't submit the form on click
  app/javascript/active_admin/features/batch_actions.js
  features/index/batch_actions.feature
Labels: type bug fix

#8458 Unify specifying label in attributes_table component
  lib/active_admin/views/components/attributes_table.rb
  spec/unit/views/components/attributes_table_spec.rb
Labels: type enhancement

#6911 Optimize count query for `pagination_total: false` option
  app/controllers/active_admin/resource_controller/decorators.rb
  lib/active_admin/views/components/paginated_collection.rb
  spec/support/matchers/perform_database_query_matcher.rb
  spec/unit/views/components/paginated_collection_spec.rb
Labels: type enhancement

#8457 Use attribute_types instead of columns_hash to determine type
  app/helpers/active_admin/display_helper.rb
  spec/helpers/display_helper_spec.rb
Labels: type enhancement

#8456 Use consistent text-like inputs selector list for CSS styles
  plugin.js
Labels: type bug fix
