Repository activeadmin/activeadmin, pull requests merged in 2024-09, with the labels that each got.

#8468 Backport Add favicon to template app to fix Rails 7.2 test suite run
  spec/support/rails_template.rb
  spec/support/templates/public/favicon.ico
Labels: type bug fix

#8469 Backport Use attribute_types instead of columns_hash to determine type
  lib/active_admin/view_helpers/display_helper.rb
  spec/unit/view_helpers/display_helper_spec.rb
Labels: type enhancement

#8470 Backport Optimize count query for pagination_total: false option
  lib/active_admin/resource_controller/decorators.rb
  lib/active_admin/views/components/paginated_collection.rb
  spec/support/matchers/perform_database_query_matcher.rb
  spec/unit/views/components/paginated_collection_spec.rb
Labels: type enhancement

#8471 perform_database_query_matcher should be truthy as long as one query matches
  spec/support/matchers/perform_database_query_matcher.rb
Labels: type bug fix

#8477 Bump `inherited_resources` requirement to `~> 2.0`
  Gemfile.lock
  activeadmin.gemspec
  gemfiles/rails_61/Gemfile.lock
  gemfiles/rails_70/Gemfile.lock
  gemfiles/rails_71/Gemfile.lock
Labels: type enhancement

#8481 Add polish translations for v4 keys
  config/locales/pl.yml
Labels: type enhancement

#8449 Drop support for Rails 6.1
  .github/workflows/ci.yaml
  .rubocop.yml
  Gemfile.lock
  activeadmin.gemspec
  gemfiles/rails_61/Gemfile
  gemfiles/rails_61/Gemfile.lock
  gemfiles/rails_70/Gemfile.lock
  gemfiles/rails_71/Gemfile.lock
  lib/active_admin/views/components/active_admin_form.rb
  spec/support/templates/views/admin/posts/_starred_batch_action_form.html.erb
Labels: type breaking change

#7437 run update_resource inside a transaction to avoid autosaving relationships through assign_attributes when the record is invalid
  app/controllers/active_admin/resource_controller/data_access.rb
  features/edit_page.feature
  features/step_definitions/attribute_steps.rb
  features/step_definitions/factory_steps.rb
  features/step_definitions/web_steps.rb
  spec/support/rails_template.rb
  spec/support/templates/admin/companies.rb
  spec/support/templates/migrations/create_companies.tt
  spec/support/templates/migrations/create_join_table_companies_stores.tt
  spec/support/templates/models/company.rb
  spec/support/templates/policies/company_policy.rb
  spec/unit/application_spec.rb
  spec/unit/resource_controller_spec.rb
Labels: type bug fix
