Repository activeadmin/activeadmin, pull requests merged in 2024-02, with the labels that each got.

#8257 Bump flowbite to v2.3.0
  package.json
  vendor/javascript/flowbite.js
  yarn.lock
Labels: type enhancement

#8242 Use an anchor for tabs component toggle
  lib/active_admin/views/components/tabs.rb
  plugin.js
  spec/unit/views/components/tabs_spec.rb
Labels: type bug fix

#8259 Drop Ruby 2.7 support
  .rubocop.yml
  activeadmin.gemspec
Labels: type breaking change

#8264 Use Tailwind's darkMode selector strategy
  lib/generators/active_admin/assets/templates/tailwind.config.js
Labels: type template update
